CSS:
  svg: css.svg
  link: https://www.w3.org/Style/CSS/
# PostCSS: postcss.svg
# SASS: sass.svg
# Stylus: stylus.svg
# Less: less.svg

# HTML5: html.svg
# Pug: pug.svg

# JavaScript: javascript-1.svg
# TypeScript: typescript.svg
# Vue: vue.svg
# Babel: babel.svg
# Prettier: prettier.svg
# Eslint: eslint.svg

# React: react.svg
# "React Query": react-query.svg

# Vite: vitejs.svg
# Webpack: webpack.svg
# NPM: npm.svg
# Gulp: gulp.svg
# Grunt: grunt.svg

# PostgreSQL: postgresql.svg
# DBeaver: dbeaver.svg
# Ruby: ruby.svg

# Git: git.svg
# "Visual Studio Code": visual-studio-code.svg
# ChatGPT: chatgpt.svg

# D3: d3.svg
# Docker: docker.svg
# Vagrant: vagrant.svg
# VirtualBox: virtualbox.svg

# - 👋 Hi, I’m @AndriiKot
# - 👀 I’m interested in Frontend Development
# - 🌱 I’m currently React, Vue, PostgreSQL

# <!---
# AndriiKot/AndriiKot is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
# You can click the Preview link to take a look at your changes.
# --->

# # My Main TOOLS:

# <div>
#   <div class="CSS">
#     <table> <tr> <td> <a href="https://www.w3.org/Style/CSS/" target="_blank"> <img src="https://upload.wikimedia.org/wikipedia/commons/3/3d/CSS.3.svg" alt="CSS Logo" width="50" height="50"> </a> </td> <td>Это логотип CSS с официального сайта W3C.</td> </tr> </table
#   <a href="https://www.w3.org/Style/CSS/" target="_blank">
#     <img src="https://upload.wikimedia.org/wikipedia/commons/3/3d/CSS.3.svg" alt="CSS Logo" width="50" height="50">
#   </a>
#   <a href="https://sass-lang.com/documentation/" target="_blank">
#     <img src="https://camo.githubusercontent.com/da79029ef5a44898077dfc91f19f8dff0546d76082556d5f22a4e209d8e5d90b/68747470733a2f2f7261776769742e636f6d2f736173732f736173732d736974652f6d61696e2f736f757263652f6173736574732f696d672f6c6f676f732f6c6f676f2e737667" alt="Sass logo" width="40" height="40">
#   </a>

#   <a href="https://stylus-lang.com/" target="_blank">
#     <img src="https://stylus-lang.com/logo.svg" alt="Stylus logo" width="40" height="50" >
#   </a>
#   <span>___Others___: </span>
#   <a href="https://postcss.org/docs/" target="_blank">
#   <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/postcss.svg" alt="PostCSS logo" width="40">
#   </a>
#   <a href="https://lesscss.org/" target="_blanl">
#   <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/less.svg" alt="Less logo" height ="25">
#   </a>
# </div>
#   <div class="HTML">
#   <a href="https://html.spec.whatwg.org/multipage/" target="_blank">
#     <img src="https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg" alt="HTML5 logo"
#     width="50" height="50">
#   </a>
#     <a href="https://pugjs.org/api/getting-started.html" target="_blank">
#   <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/pug.svg" alt="Pug logo" width=40">
#     </a>
#   </div>
#     <div class="JS">
#       <a href="https://ecma-international.org/publications-and-standards/standards/" target="_blank">
#     <img src="https://github.com/voodootikigod/logo.js/blob/master/js.png" alt="JS logo" width="50" height="50">
#   </a>
#       <a href="https://react.dev/" target="_blank" >
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/react-2.svg" alt="React logo" width="45">
#       <a>
#       <a href="https://vuejs.org/" target="_blank">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/vue-9.svg" alt="Vue logo" width="45">
#       </a>
#         <a href="https://eslint.org/docs/latest/" target="_blank">
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/eslint-1.svg" alt="Eslint logo" width="40">
#         </a>
#         <a href="https://prettier.io/" target="_blank">
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/prettier-2.svg" alt="Prettier logo" width="40">
#         </a>
#     </div>
#     <div class="Module Bandler">
#       <a href="https://vitejs.dev/" target="_blank">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/vitejs.svg" alt="Vite logo" width="50">
#       </a>
#       <a href="https://webpack.js.org/" target="_blank">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/webpack-icon.svg" alt="Webpack logo" width="50">
#       </a>
#       <a href="https://docs.npmjs.com/" target="_blank">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/npm.svg" alt="Npm logo" height="25">
#       </a>
#       <span>__Others:__</span>
#       <a href="https://gulpjs.com/" target="_blank">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/gulp-1.svg" alt="Gulp logo" height="40">
#       </a>
#       <a href="https://gruntjs.com/getting-started" target="_blanl">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/grunt-1.svg" alt="Grunt logo"
#         height="50">
#       </a>
#     </div>
#     <div class="BAKEND">
#       <a href="https://www.postgresql.org/docs/" target="_blank">
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/postgresql.svg" alt="PostreSQL logo" width="50">
#       </a>
#       <a href="https://dbeaver.com/docs/dbeaver/" targer="_blanl">
#       <img src="https://upload.wikimedia.org/wikipedia/commons/b/b5/DBeaver_logo.svg" alt="DBeaver logo" width="60">
#       </a>
#       <a href="https://ruby-doc.org/" target="_blank" >
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/ruby.svg" alt="Ruby logo" width="45">
#       </a>
#     </div>
#       <div class="OTHER">
#         <a href="https://www.git-scm.com/doc" tarrget="_blank">
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/git-icon.svg" alt="Git logo" width="50">
#         </a>
#         <a href="https://code.visualstudio.com/docs" target="_blank">
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/visual-studio-code-1.svg" alt="VsCode logo" width="45">
#         </a>
#         <a href="https://chatgpt.com/auth/login" target="_blank">
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/chatgpt-1.svg" alt="ChatGPT logo" width="45">
#         </a>
#         <a href="https://conemu.github.io/blog/2023/07/24/Build-230724.html" target="_blank">
#         <img src="https://upload.wikimedia.org/wikipedia/commons/d/dc/ConEmu_icon.png" alt="ConEmu logo" width="45">
#         </a>
#       </div>
#       <div class="Deployd">
#         <a href="https://docs.docker.com/" target="_blank">
#         <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/docker-4.svg" alt="Docker logo" width="60">
#         </a>
#         <a href="https://www.virtualbox.org/" target="_blank">
#           <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/virtualbox.svg" alt="VirtualBox logo" height="40">
#         </a>
#       <img src="https://github.com/AndriiKot/PROJECTS/blob/main/assets/vagrant.svg" alt="Vagrant logo" width="45">
#       </div>
# </div>

