arrCSS:
  - CSS
  - PostCSS
  - SASS
  - Stylus
  - Less
  - Bootstrap
arrHTML:
  - HTML5
  - Pug
arrJS:
  - JavaScript
  - TypeScript
  - Eslint
  - Prettier
  - DOM
arrReact:
  - React
  - React Query
  - Vue
  - Babel
arrNodeJs:
  - NodeJS
  - NPM
  - Yarn
  - Express
  - Electron
arrSQL:
  - PostgreSQL
  - SQLite
  - JSON
  - YAML
  - DBeaver
  - Ruby
arrTaskRuner:
  - Vite
  - Webpack
  - Gulp
  - Grunt
arrProjectManager:
  - Git
  - Visual Studio Code
  - ChatGPT
  - ConEmu
  - FarManager
  - Curl
arrApplicationDev:
  - Docker
  - VirtualBox
  - Vagrant

